version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: museum_mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=museum

  redis:
    image: redis:7-alpine
    container_name: museum_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: museum_backend
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/museum
      - REDIS_URI=redis://redis:6379
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://103.178.233.206}
      - CLOUDINARY_URL=cloudinary://525596288476341:zLtV43liy-USXPkPDMmscuXum0k@djkif9ubs
      - CLOUDINARY_CLOUD_NAME=djkif9ubs
      - CLOUDINARY_API_KEY=525596288476341
      - CLOUDINARY_API_SECRET=zLtV43liy-USXPkPDMmscuXum0k
      - CLOUDINARY_ROOT_FOLDER=museum
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=huynhtanlocpp09@gmail.com
      - SMTP_PASS=csvopdsnfnonsuxy
      - SMTP_FROM="Bảo Tàng Lịch Sử TP.HCM <huynhtanlocpp09@gmail.com>"
    volumes:
      - uploads_data:/app/backend/public/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: museum_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local
  redis_data:
    driver: local
